version: "3.9"

services:
  test_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - test_net
    environment:
      - DB__HOST=postgres
      - DB__NAME=test_db
      - DB__USER=test_user
      - DB__PASSWORD=test_password

  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_db" ]
      interval: 10s
      timeout: 2s
      retries: 10
    tmpfs:
      - /var/lib/postgresql/data:rw
    networks:
      - test_net

networks:
  test_net:
