version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: multi-stage.Dockerfile
      target: prod
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net

  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_prod
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}" ]
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

networks:
  net:

volumes:
  postgres_data:
