"""create superheroes table

Revision ID: 98cf8338630e
Revises: 
Create Date: 2025-08-08 18:44:41.905605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cf8338630e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superheroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('combat', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_superheroes')),
    sa.UniqueConstraint('name', name=op.f('uq_superheroes_name'))
    )
    op.create_index(op.f('ix_superheroes_id'), 'superheroes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_superheroes_id'), table_name='superheroes')
    op.drop_table('superheroes')
    # ### end Alembic commands ###
